const ACTION_TYPES = {
  INCREASE_BREAK: 'INCREASE_BREAK',
  DECREASE_BREAK: 'DECREASE_BREAK',
  INCREASE_SESSION: 'INCREASE_SESSION',
  DECREASE_SESSION: 'DECREASE_SESSION',
  START_OR_STOP: 'START_OR_STOP',
  SWAP_MODE: 'SWAP_MODE',
  RESET: 'RESET'
}

export default ACTION_TYPES